# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba0ee5afc2f4f083b978affe468931d004400de60719020cf5aa216f4b512229296bc0fff034ea7a0889789aa78f66407e034ce40315fe8407ac13a2b33d9e34

test:
  secret_key_base: 2cd3af978884cafb62c4132204146b34b1ffb62ad7cf94ef2fff02293de4330d1264dca990ea6c4c86720375d7ba4e51a9badc83a22d4aae6a172a889fd43720

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
